  # https://aws.amazon.com/blogs/storage/persistent-storage-for-kubernetes/

apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-postgresql
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0fa68d8aa00b4e4ec::fsap-07a5e30585dc00bcb