apiVersion: v1
kind: Pod
metadata:
  name: upperlower-pod
  labels:
    app: upperlower
spec:
  containers:
    - name: upperall
      image: jdmedeiros/upperall:latest
      imagePullPolicy: Always
      volumeMounts:
        - name: persistent-storage
          mountPath: /data
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: efs-claim
